function [LP] = struct_LP()

    LP = struct(    'Path',     [], ...
                    'X',        [], ...
                    'Y',        [], ...
                    'Z',        [], ...
                    'Names',    []);

end

