function [acquisition] = struct_acquisition()

    acquisition = struct(   'Path',             [], ...
                            'Name',             [], ...
                            'Data',             [], ...
                            'NbData',          [], ...
                            'DataSize',        [], ...
                            'PixelSize',       [], ...
                            'LP',               struct_LP(), ...
                            'Maps',             struct_map());

end

