function [maps] = struct_map()
    Appearance = {{'DMD',                    'map_dmdCoefficients'}, ...
                  {'DMDInvariant',           'map_dmdInvariantCoefficients'}, ...
                  {'HSH',                    'map_hshCoefficients'}, ...
                  {'PTM',                    'map_ptmCoefficients'}, ...
                  {'RBF',                    'map_rbfCoefficients'} };
             
    Statistic = {{'Mean',                  'map_mean'}, ...
                 {'Median',                'map_median'}, ...
                 {'StandardDeviation',    'map_standardDeviation'}, ...
                 {'Skewness',              'map_skewness'}, ...
                 {'Kurtosis',              'map_kurtosis'}, ...
                 {'VariationCoefficient', 'map_variationCoefficient'}, ...
                 {'Energy',                'map_energy'}, ...
                 {'Entropy',               'map_entropy'}, ...
                 {'Max',                   'map_max'}, ...
                 {'Min',                   'map_min'}, ...
                 {'DynamicRatio',          'map_dynamicRatio'}, ...
                 {'Mode',                  'map_mode'}, ...
                 {'Quartile1',             'map_quartile1'}, ...
                 {'Quartile3',             'map_quartile3'} };
             
    Geometric = {{'Normal',                'map_normal'}, ...
                 {'Dx',                    'map_dx'}, ...
                 {'Dy',                    'map_dy'}, ...
                 {'Dz',                    'map_dz'}, ...
                 {'Kxx',                   'map_kxx'}, ...
                 {'Kxy',                   'map_kxy'}, ...
                 {'Kyy',                   'map_kyy'}, ...
                 {'Kmin',                  'map_kmin'}, ...
                 {'Kmax',                  'map_kmax'}, ...
                 {'Kmean',                 'map_kmean'}, ...
                 {'Kgaussian',             'map_kgaussian'}, ...
                 {'DipAngle',              'map_dipAngle'}, ...
                 {'AzimuthAngle',          'map_azimuthAngle'}, ...
                 {'AngularNormal',         'map_angularNormal'}, ...
                 {'RiseX',                 'map_riseX'}, ...
                 {'RiseY',                 'map_riseY'}, ...
                 {'RiseXY',                'map_rise'}, ...
                 {'KMehlum',               'map_kmehlum'}, ...
                 {'ShapeIndex',            'map_shapeIndex'}, ...
                 {'Curvedness',            'map_curvedness'}, ... 
                 {'KminVector',            'map_kminVector'}, ... 
                 {'KmaxVector',            'map_kmaxVector'}};    
    
    for i=1:length(Appearance)
        maps.Data.(Appearance{i}{1}) = [];
        maps.Functions.(Appearance{i}{1}) = Appearance{i}{2};
    end
    
    for i=1:length(Statistic)
        maps.Data.(Statistic{i}{1}) = [];
        maps.Functions.(Statistic{i}{1}) = Statistic{i}{2};
    end
    
    for i=1:length(Geometric)
        maps.Data.(Geometric{i}{1}) = [];
        maps.Functions.(Geometric{i}{1}) = Geometric{i}{2};
    end

end

